// random 500 indonesian words with minimum 4 characters and max 8 characters
export const WORDS = [
  "kucing", "anjing", "burung", "ikan", "sapi", "kuda", "ayam", "bebek", "kelinci", "tikus",
  "laptop", "hp", "kamera", "jam", "kunci", "dompet", "tas", "sepatu", "baju", "celana",
  "motor", "mobil", "kapal", "kapal", "kereta", "sepeda", "bus", "truk", "pesawat", "perahu",
  "kafe", "toko", "bank", "rumah", "kantor", "pasar", "mall", "apotek", "klinik", "hotel",
  "makan", "minum", "roti", "nasi", "daging", "sayur", "buah", "susu", "telur", "keju",
  "musik", "lagu", "film", "buku", "cerita", "novel", "majalah", "koran", "komik", "puisi",
  "olah", "sepak", "bola", "tenis", "renang", "lari", "lari", "gym", "yoga", "dansa",
  "libur", "wisata", "piknik", "tenda", "jalan", "renang", "surf", "ski", "travel", "trip",
  "keluarga", "teman", "sahabat", "tetangga", "guru", "dokter", "polisi", "tukang", "satpam", "pilot",
  "hobi", "koleksi", "gambar", "foto", "video", "game", "puzzle", "catur", "monopoli",
  "bunga", "pohon", "daun", "akar", "buah", "biji", "tanah", "air", "api", "udara",
  "mata", "hidung", "mulut", "telinga", "tangan", "kaki", "kepala", "rambut", "gigi", "lidah",
  "merah", "biru", "hijau", "kuning", "hitam", "putih", "abu", "coklat", "pink", "ungu",
  "besar", "kecil", "tinggi", "pendek", "gemuk", "kurus", "panjang", "pendek", "lebar", "sempit",
  "cepat", "lambat", "mudah", "sulit", "baik", "buruk", "baru", "lama", "mahal", "murah",
  "satu", "dua", "tiga", "empat", "lima", "enam", "tujuh", "delapan", "sembilan", "sepuluh",
  "senin", "selasa", "rabu", "kamis", "jumat", "sabtu", "minggu", "hari", "minggu", "bulan",
  "tahun", "waktu", "jam", "menit", "detik", "pagi", "siang", "sore", "malam", "tengah",
  "makan", "minum", "tidur", "bangun", "mandi", "cuci", "pakai", "lepas", "buka", "tutup",
  "jalan", "lari", "duduk", "berdiri", "naik", "turun", "masuk", "keluar", "datang", "pergi",
  "baca", "tulis", "gambar", "warna", "cat", "kuas", "kertas", "pensil", "pena", "buku",
  "sekolah", "belajar", "mengajar", "guru", "murid", "kelas", "ujian", "nilai", "tugas",
  "kerja", "kantor", "bos", "karyawan", "gaji", "uang", "bank", "kartu", "pinjam",
  "beli", "jual", "harga", "diskon", "promo", "toko", "pasar", "mall", "online", "offline",
  "rumah", "kamar", "dapur", "kamar", "toilet", "garasi", "halaman", "pintu", "jendela", "atap",
  "mobil", "motor", "bus", "taksi", "kereta", "pesawat", "kapal", "sepeda", "jalan", "jalan",
  "makan", "sarapan", "makan", "makan", "cemilan", "kue", "permen", "coklat", "es", "kopi",
  "teh", "susu", "air", "jus", "soda", "bir", "anggur", "minuman", "botol", "gelas",
  "pakaian", "baju", "celana", "rok", "jaket", "kaos", "kemeja", "dasi", "topi", "sepatu",
  "sandal", "kaos", "kaus", "celana", "rok", "dress", "jas", "mantel", "syal", "ikat",
  "keluarga", "ayah", "ibu", "anak", "kakak", "adik", "kakek", "nenek", "paman", "bibi",
  "sepupu", "menantu", "mertua", "saudara", "teman", "sahabat", "tetangga", "kenalan", "orang", "manusia",
  "binatang", "hewan", "kucing", "anjing", "burung", "ikan", "sapi", "kambing", "ayam", "bebek",
  "kelinci", "tikus", "ular", "kadal", "katak", "kupu", "laba", "semut", "lebah", "nyamuk",
  "pohon", "bunga", "daun", "akar", "buah", "biji", "tanah", "pasir", "batu", "gunung",
  "laut", "sungai", "danau", "air", "hujan", "salju", "es", "api", "asap", "angin",
  "matahari", "bulan", "bintang", "langit", "awan", "pelangi", "kilat", "guntur", "badai", "topan",
  "musim", "panas", "dingin", "hujan", "kemarau", "semi", "gugur", "dingin", "panas", "lembab",
  "negara", "kota", "desa", "jalan", "jalan", "jembatan", "taman", "toko", "pasar", "mall",
  "rumah", "gedung", "menara", "benteng", "istana", "masjid", "gereja", "kuil", "candi", "monumen",
  "sejarah", "masa", "lalu", "sekarang", "masa", "depan", "zaman", "era", "periode", "abad",
  "tahun", "bulan", "minggu", "hari", "jam", "menit", "detik", "waktu", "tanggal", "kalender"
]